### ISSUE TITLE
Score data isn't reset when changing state to ScoreSelect

### ISSUE THREAD

**Issue by S1n1st3rn3ss** [486c/rosu-memory#17]
Gameplay data (300/100/50/0, combo, etc) doesn't get reset upon entering song select screen, only when starting a new beatmap

**Comment by 486c** [comment]
The only way to fix this is to store previous state and check if it changed.

**Comment by uzervlad** [comment]
Is that an issue though? You wouldn't use that data outside of gameplay anyway, right?

**Comment by S1n1st3rn3ss** [comment]
> You wouldn't use that data outside of gameplay anyway

If an overlay stays on the screen permanently (most simpler overlays do), it will show incorrect data when moving from gameplay to song select, forcing overlay creators to wipe that data themselves, can be slightly annoying

**Comment by 486c** [comment]
> forcing overlay creators to wipe that data themselves, can be slightly annoying
Yep i agree, i thinks it's much simpler to wipe it on rosu-memory side. Storing previous state cost and checking it every read cost us almost nothing. But then there's another problem - port counters properly to avoid unnecessary work that (e.g. as stated earlier wiping data when changing to `SongSelect` from `Playing` state) rosu-memory already does/will be doing in the future. I think we should document those small beneficial differences pretty clear so counter creators could tweak their code?

**Comment by S1n1st3rn3ss** [comment]
> I think we should document those small beneficial differences pretty clear so counter creators could tweak their code?

I could get to that at some point, yeah

**Comment by 486c** [comment]
fixed in 8c8dac736a3f7571cbd36482c30c51164ee290a6
