### ISSUE TITLE
Reading loop occasionally resets

### ISSUE THREAD

**Issue by S1n1st3rn3ss** [486c/rosu-memory#45]
Loop of finding osu folder -> reading static signatures -> actual reading loop seems to break on Windows machines. Requires platform-specific investigation, as I was unable to replicate the issue even once

Example output:
![image](https://github.com/486c/rosu-memory/assets/49232762/f22ee2ab-11d9-400b-b3a4-ab5d9eb662c0)

Seems to be related to #44 in some form, as I've not seen anyone replicate only one of the two so far

**Comment by 486c** [comment]
During my short investigation found that's highly connected with cutting-edge and spectating. Windows probably doesn't related to this

**Comment by 486c** [comment]
Pretty much happens only if values is not ready yet, we can really can't do anything about it, just reset reading loop and pray that values gonna appear in next read cycle 😄 

Feel free to reopen
