### ISSUE TITLE
pp is 0 on results screen and song select

### ISSUE THREAD

**Issue by respektive** [486c/rosu-memory#48]
Should show the pp for the score when clicking on a score on the leaderboards or after coming from gameplay. 

For song select it should probably just show the SS pp for the selected beatmap and mods.

**Comment by 486c** [comment]
> Should show the pp for the score when clicking on a score on the leaderboards or after coming from gameplay.
Looks like an exact opposite of #17 :smiley:

**Comment by 486c** [comment]
Done in f279eced1fee6bd7a0784114d5a0dac6cf070935 and acfb070a2bbfea2c77e298228fe22893e0b9ae29

In `ResultScreen`, `current_pp` now shows pp of the corresponding score
In `SongSelect`, shows `ss_pp` of currently selected map
