### ISSUE TITLE
Converted sr not calculated correctly for converted catch maps

### ISSUE THREAD

**Issue by Inconn** [486c/rosu-memory#55]
Noticed in the process of investigating #52, it seems that catch sr and probably pp isn't calculated correctly at all, and it only gives the osu!standard sr.

**Comment by Inconn** [comment]
this is specifically for converted beatmaps, not for maps that are osu!catch only

**Comment by 486c** [comment]
Fixed in 1d8ff47be215bc458b146ab30f4a9b2025d4c53d and 0512cbb904a2b971da4869bc1c7e21da3cbaa16d
For details read #57
