### ISSUE TITLE
"data.fc_pp" doesn't show actual "if fc" pp

### ISSUE THREAD

**Issue by FlySlime** [486c/rosu-memory#64]
I'm assuming that the purpose of `data.fc_pp` is to display the pp value for an fc if you didn't sliderbreak/miss. However this doesn't seem to be the case. It seems like it (almost) displays the value if you got an fc INCLUDING the misses, which is obviously not possible. I'll upload pictures showcasing the problem and the [replay](https://mega.nz/file/Rpo2hLhY#ezmgkRDac3cc3MpZNrgQr_PIzeXTsbfYLCqxKwxhXyA).

**The value displayed on the key overlay:**
![image](https://github.com/486c/rosu-memory/assets/50276341/ce204e26-28af-4f97-a83d-3ef1f2597e0a)

**The pp for "full combo" with the misses:**
![image](https://github.com/486c/rosu-memory/assets/50276341/a99e913d-e12d-4bce-99d1-45c2d73da043)

**The actual pp for full combo:**
![image](https://github.com/486c/rosu-memory/assets/50276341/2cb5e164-1d61-459a-9e13-9a1e976d758d)

**Comment by 486c** [comment]
fixed in bde582c2ecc1393885e2ffa46fee59f25e335518
