### ISSUE TITLE
Takes a minute or so for the overlay to start

### ISSUE THREAD

**Issue by FlySlime** [486c/rosu-memory#66]
As of the latest commits, it now takes slightly longer for the key overlays to begin working.

**Comment by 486c** [comment]
By "key overlays" you mean `data.keyoverlay` values? Or `rosu-memory` in general? If second option then i have to ask is reading static values is slow for you (aka everything before `Starting reading loop` message) or everything after it (aka after `Starting reading loop` message)?

also if you compiled `rosu-memory` by yourself check that you didn't forgot `--release` flag

**Comment by FlySlime** [comment]
The problem was me not compiling with the `--release` flag 😛. All is good now!
